### ISSUE TITLE
Test openNebula API failed

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#102]
The openNebula test create API failed, which is normal :-) since this test, currently, only runs on our lab with an OpenNebula instance running. 
(BTW in the feature we should have an openNebula instance for tests somewhere).
So the action to take:
1. Before pushing a version on git please make sure that your test will be ignored. This can be done by adding the "@Ignore" annotation (http://junit.sourceforge.net/javadoc/org/junit/Ignore.html)
2. @jbruggem The error of described by the test is not the connection error, is much more weird: org/opennebula/client/ClientConfigurationException : Unsupported major.minor version 51.0
(http://dev.roq-messaging.org/ci/job/RoQ/337/org.roqmessaging.core$roq-IaaS/testReport/org.roqmessaging.core/TestOpenNebulaAPI/testCreate/)

This usually happens when the class were compiled with a Java compiler having an higher version than the JRE executing the test. So action check the Java version installed in the CI host (as there is no JDK defined in the Jenkins)

**Comment by cduverne** [comment]
Hello,

I added the @Ignore, I think it's OK now :)
Let's see if our Jenkins friend is happy now :)
Cheers
CyD

**Comment by sskhiri** [comment]
@cduverne  can you check whether open nebula provides a fake oneD XML rpc interface for test purpose ? That would be great for CI automatic tests.

**Comment by cduverne** [comment]
OpenNebula provides a dummy driver for their installation, I'd suggest to have a standalone environment on the CI server to have a full test suite.
