### ISSUE TITLE
libzmq-dbg libzmq-dev libzmq1 version 3 are not compatible

### ISSUE THREAD

**Issue by dugauthier** [roq-messaging/RoQ#108]
When using the latest versions of libzmq-dbg libzmq-dev libzmq1 from the chris-lea PPA (version 3), RoQ refuses to start (does not find libzmq.so.1).

Reverting to version 2 (official ubuntu repo) fixes the problem.

**Comment by sskhiri** [comment]
Closed with the update of ZMQ 3.0 in RoQ.
