### ISSUE TITLE
Start GCM : background

### ISSUE THREAD

**Issue by cduverne** [roq-messaging/RoQ#113]
When starting the GCM at boot, the console is blocked by the command "java etc...", the GCM starts correctly, but the behaviour is confusing...

Is this possible to run this command in background ?

Thanks
CyD

**Comment by sskhiri** [comment]
did you try http://stackoverflow.com/questions/12102270/run-java-jar-file-on-a-server-as-background-process ?
2 solutions are suggested, I have already used nohup in previous projects.

**Comment by cduverne** [comment]
Indeed I've already seen nohup, but i didn't use it properly, I'll try this tonight :)

**Comment by cduverne** [comment]
Yeah !!!
Nohup did the trick, when used properly :p 

I'll be able to create a contextualized VM for OpenNebula launching RoQ :)

**Comment by cduverne** [comment]
I've got a working OPENNEBULA image !!!!! :p 
Congratulations to me !
:p

**Comment by sskhiri** [comment]
Congrat 2 you !! on the next hack night we would finally be able to test the elastic behavior ! Now that the test loader is ready everything is in place !
Cool ...
