### ISSUE TITLE
Stream logs to backend/web client

### ISSUE THREAD

**Issue by dugauthier** [roq-messaging/RoQ#114]
Investigate and, if possible, implement the streaming of logs (based on a configurable log level) to the backend and the web console.

**Comment by jbruggem** [comment]
Could you elaborate on what logs you are referring to? Is it the log4j output of the different elements (GCM, Host, etc)? Is it the messages broadcasted by these components?

**Comment by sskhiri** [comment]
On  hold until clearer requirements.
