### ISSUE TITLE
Checking the static behavior

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#117]
The objective is to test the static configuration under load, for instance:
- 1 physical nodes with 2 exchanges each.
- 2 physical nodes with 2 exchanges each.
- 3 physical nodes with 2 exchanges each.

And checking:
- Memory footprint and memory leak (JProfiler)
- CPU usage
- Message losts

**Comment by sskhiri** [comment]
@cduverne, I will start to work on this issue, I will need to have machine on the lab. Is it possible to update the RoQ image in order to get the last stable version ?
Thanks !

**Comment by cduverne** [comment]
Hello,

Yes it is !
Time frame ?

Cheers
Cyrille

Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Sabri Skhiri  
Date : 
A : roq-messaging/RoQ  
Cc : Cyrille Duverne  
Objet : Re: [RoQ] Checking the static behavior (#117) 

@cduverne, I will start to work on this issue, I will need to have
machine on the lab. Is it possible to update the RoQ image in order to
get the last stable version ?
Thanks !

---

**Comment by sskhiri** [comment]
It would be great to get it either for April 20. In the meantime I will prepare the test cases and the memory profilers.

**Comment by cduverne** [comment]
Ok, it will be done by then.

Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Sabri Skhiri  
Date : 
A : roq-messaging/RoQ  
Cc : Cyrille Duverne  
Objet : Re: [RoQ] Checking the static behavior (#117) 

It would be great to get it either for April 20. In the meantime I
will prepare the test cases and the memory profilers.

---

**Comment by sskhiri** [comment]
The first performance and memory analysis show that RoQ (Exchange and monitor at least) is very stable. However we notice the we spent 10 ms just to decode the producer ID for statistic. Indeed, this stat will define the most productive producer so a sampling can be a problem.
I propose to test other solutions such as Kryo (http://code.google.com/p/kryo/) or Guava.

**Comment by sskhiri** [comment]
I found an excellent post about performance of new String(byte[]) : http://www.javacodegeeks.com/2010/11/java-best-practices-char-to-byte-and.html

**Comment by jbruggem** [comment]
Interesting stuff!

This said, I'm more concerned with our overheads (number of processes,
queues, etc) than our speed right now.

Jehan Bruggeman
+32 496 67 43 48

**Comment by sskhiri** [comment]
Sure, but in this task I am more looking at micro memory leak, cpu time on methods. So if I can do housekeeping in the same time it is interesting.

**Comment by sskhiri** [comment]
I will include the evaluation of the automatic load balancing and publisher allocation to Exchange:

## Test 1: starting a producer after the cold start condition
1. Starting a test load with 2 Publishers and 3 Subscribers. The load must be > 10% than the MAX exchange limit in order to overcome the cold start condition. 
2. After 1 min, when we are sure that the cold start condition is not applicable we start a new producer and we check the allocation.

## Test 2: Dynamic allocation
1. Starting a test load with 4 Publishers (x, y, z, w) and 3 Subscribers. The rate of X, Y, Z are 20 % (each) of the rate of W. After 2 mins the total throughput in b/min must be > than the exchange limit and should triger a re-balance of W.
2. Starting a new Exchange after 1 min. Without any publisher connected.
3. We should observe the migration of the publisher w to exchange 2.
