### ISSUE TITLE
Create clean Stop for RoQ

### ISSUE THREAD

**Issue by cduverne** [roq-messaging/RoQ#120]
Hello,

We should create a clean stop function/method/anything to stop a running RoQ

Cheers
CyD

**Comment by cduverne** [comment]
The container already exists in /etc/init.d/RoQ
The shutdown.sh script needs to be created.

When done I'll update the RoQ-OpenNebula Image.

**Comment by sskhiri** [comment]
Same as issue #111.

**Comment by sskhiri** [comment]
A new Script has been added in the pkg-script directory (that are copied by Jenkins in the bin directory of RoQ install home): stopRoQ.sh
For stopping:
1. Stopping the HCM:  go in the RoQ home/bin of the host and type: ./stopRoQ.sh HCM
2. Stopping the GCM : go in the RoQ home/bin of the host and type: ./stopRoQ.sh GCM

@cduverne can you update the service init.d config for proper "service roq stop" in the RoQ VM template?
