### ISSUE TITLE
GimmeRoQ.sh : Error when installing back-end management

### ISSUE THREAD

**Issue by cduverne** [roq-messaging/RoQ#129]
Hello, 

The GimmeRoQ script is giving this error when trying to install the back-end management : 

"Build failed:  -> task failed (err #1): {task: cxx binding.cc ->
binding_1.o}
npm ERR! error installing zmq@2.0.3
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/runforcover
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/difflet
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/buffer-equal

npm ERR! zmq@2.0.3 preinstall: `node-waf clean || (exit 0); node-waf
configure build`
npm ERR! `sh "-c" "node-waf clean || (exit 0); node-waf configure
build"` failed with 1
npm ERR! 
npm ERR! Failed at the zmq@2.0.3 preinstall script.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || (exit 0); node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.2.0-39-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/lib/RoQ/RoQ/roq-backend
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message zmq@2.0.3 preinstall: `node-waf clean || (exit 0);
node-waf configure build`
npm ERR! message `sh "-c" "node-waf clean || (exit 0); node-waf
configure build"` failed with 1
npm ERR! errno {}"

Thanks to have a look to this.
Cheers
CyD

**Comment by jbruggem** [comment]
It is to be expected, as roq-backend has not been updated yet to the new version of ZeroMQ we're using.

In the future, Please put issues related to roq-backend [in the right bug tracker](https://github.com/roq-messaging/roq-backend/issues).
