### ISSUE TITLE
Test Scripts

### ISSUE THREAD

**Issue by cduverne** [roq-messaging/RoQ#14]
As suggested yesterday with Nam, it would be interesting to have a script set to see RoQ in action.

This might be useful for the tests since we could use these scripts to make the scenarii running.

**Comment by sskhiri** [comment]
I propose to have 2 kinds of tests:
1. Junit test for simple local test
2. Deployable simulation environment (local or on cluster). For this one, I would I see different simulation classes. Those classes must be installed and launched from a confiuration file (IP address + location to install + Credential). A script should install and load the libraries on each machine present in the config file and start the simulation classes. 

Concerning the JUnit test, I do not see any reason to have such script.

**Comment by sskhiri** [comment]
In a first step we need to define the objectives of the Simulation framework, and then, according to the objectives defining what would be the shape of this module.

**Comment by sskhiri** [comment]
A new simulation module have been created and all the main methods have been moved. In addition Junit test have been created in Core. Still need to define a real test plan.

**Comment by sskhiri** [comment]
The ZLoadPub and ZLoadSub must be re-factored for integrating the Simulation module.

**Comment by cduverne** [comment]
The test scripts might be set up on the following environment :
- 5 machines
  -> Including a master machine, executing the tests while reading a configuration file and pushing the tests to the 4 others

Tests' content :
- Configuration file :
  -> Hosts config.
  -> .jar downloading from jenkins
  -> ...

Test plan : x messages/min during y minutes

**Comment by sskhiri** [comment]
On hold, waiting for the cluster configuration approach.

**Comment by sskhiri** [comment]
Moved to task #105
