### ISSUE TITLE
Mavenize ZeroMQ & having a functional Build

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#16]
The objective of this story is to have a fully functional maven build. Currently ZeroMQ is not a maven module, therefore, it needs to be installed manually (which BTW involved a compilation and installation). IS there any way to have a module of ZeroMQ for WIN and Linux platform ? 
We can also directly asked to Pieter for this, anyway we will need a kind of light integration if we want to have modules that follow the ZeroMQ evolutions.

**Comment by jbruggem** [comment]
My understanding is that the build is now as mavenized as possible. Do you agree to close this?

**Comment by sskhiri** [comment]
OK !
