### ISSUE TITLE
Test definition 

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#2]
The project should contain a set of test plans that must be used for checking the project after each build.

**Comment by sskhiri** [comment]
I think the test plan should be one of the prior story to implement, as it will be used for validating the first re-factoring phase.

**Comment by cduverne** [comment]
Do we mean test scenarii ? Like "a new producer arrives, what's happening ?"or "an exchange is shut down, is the system reacting accordingly ?"

If so, I'd like to take this in charge, so it will make the solution more concreat for me :)

**Comment by sskhiri** [comment]
Actually it is really close to your "Test scenari", even the same. This is:
1. A set of test plan or scenari 
2. Their implementation

This should be used as regression test when we will re-factor or update the code.I think we can merge the Issue 14 with this one.

Concerning the Test itself, yes you are right, it is basically:
- Setup of an exchange + 1 prod + 1 listener
- than we increase the number of Listener and we check the result
- than we increase the number of producer, and we check the result
- than we increase the number of exchange and we check the result
  ...

**Comment by sskhiri** [comment]
As explained in the google group I have created JUnit test. However, maven needed to get the right java.library.path to zmq.so libs. It seems that the standard config does not works:
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemProperties>
                        <property>
                            <name>java.library.path</name>
                            <value>/usr/local/lib</value>
                        </property>
                    </systemProperties>
                </configuration>
    </plugin>

I had to find a tweak as following:
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <forkMode>once</forkMode>
                    <workingDirectory>target</workingDirectory>
                    <argLine>-Djava.library.path=/usr/local/lib</argLine> 
                </configuration>
    </plugin>

Now the basic test are working with mvn test !

**Comment by sskhiri** [comment]
Thanks Optimus, the Unit test description is on https://github.com/roq-messaging/RoQ/wiki/Unit-Tests
