### ISSUE TITLE
Web Console mockups + usage scenario

### ISSUE THREAD

**Issue by dugauthier** [roq-messaging/RoQ#31]

**Comment by dugauthier** [comment]
If you can think of use cases for the Web Console, please share in this comment thread.

Currently, I can think of
- Listing Queues (with quick actions for each and link to details)
- For each Queue, a page with the number of exchanges, the stats, the possible actions, ...

QDU.

**Comment by nltran** [comment]
Great, let's share ideas!

As the main entry point to the status and configuration of the RoQ messaging service, what I consider important for the user to have is on this console are: 
- Information on physical hosts in the queue, related system metrics (CPU, memory, bandwidth, ...)
- Messaging stats: 
  *\* amount of producers, listeners connected to the service, 
  *\* distribution of message topics
- A dasboard view of these elements 

If we are to provide the auto scaling and management components of RoQ, the web console can also permit to
- Define KPI thresholds
- Define max amount of exchanges

**Comment by dugauthier** [comment]
Note to self:
- 1 physical machine can be linked to several Exchanges, supporting one or several Queues
- 1 queue is running several exchanges hosted on one or several physical hosts.
- Interface should allow to navigate starting from Hosts or Queues

**Comment by dugauthier** [comment]
Current structure of the web console:
- Home Page
  *\* Queues List
  **\* Queue Management <em>(One per Queue)</em>
  *\* Hosts List
  **\* Host Management <em>(One per Queue)</em>
