### ISSUE TITLE
Management console back-end architecture

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#44]
in collaboration with @dugauthier. 

The objective is to design the management console back-end architecture. The objective is to provide a web console where the user can:
- view current and past state of queues & exchanges (including detailed statistics)
- define auto-scaling rules according to some KPIs
- handle the auto-scaling itself (either on a local cloud or on external cloud providers such as AWS)

Should be in-line with issue #31 and #43.

Expected results of the task will be
- to define a set of techno to implement the console
- architecture
- a description language for AS rules

**Comment by sskhiri** [comment]
@jbruggem  is there any other tasks for this issues ? If there is can you please list them or create new associated tickets ?

**Comment by jbruggem** [comment]
Let's go over what was required:
- view current and past state of queues & exchanges (including detailed statistics) => roq-backend can store the current state of queues and exchange, but does not provide any history (we keep the 5 last statuses but don't expose them to the CLI and Web interface).
- define auto-scaling rules according to some KPIs => OK in the CLI. Not done in the web interface or in the web-api
- handle the auto-scaling itself (either on a local cloud or on external cloud providers such as AWS) => This is not handled by RoQ backend anymore.

So at least a bit of work on the API and the web interface for autoscaling I suppose. And there's also probably a need for a "documentation ticket".

**Comment by sskhiri** [comment]
OK, please create the tickets as long as they come in your mind, in the next hack night, we will define the content of the next sprint and close Sprint 4. About the Roq Core doc on autoscaling, the BSON API are already documented in https://github.com/roq-messaging/RoQ/wiki/Auto-Scaling-configuration.
@dugauthier  please sync up your tickets on the roq management console front end.
Thanks !!!

**Comment by sskhiri** [comment]
Moved to roq back-end.
