### ISSUE TITLE
Web site content

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#5]
Defining the content of the web site in term of:
- Presentation of the project
- High level view of the technical aspects

This content must be the minimum required for communication, the other things such as video, webcast, etc. will be defined later.

**Comment by jbruggem** [comment]
We will migrate everything to the secondary ena server. To this end with must check with all stakeholders that we can indeed wipe it clean and install a clean distrib with the website and a CI stack.

**Comment by sskhiri** [comment]
Thanks Cortex (dugauthier) the web site is great ! http://roq-messaging.org
This issues is continued on http://roq-messaging.org
