### ISSUE TITLE
Management console wiring with Front end

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#85]
The management console front end and back end are almost finished, we still need to:
1. Wire them each other
2. Integrate the RoQ BSON interface
3.  To think about the packaging strategy from the CI and the RoQ package download

@dugauthier, please plan to see @jbruggem for the integration phase, it should not be so long !

**Comment by jbruggem** [comment]
I think this can be closed. @sskhiri , can you confirm?

**Comment by sskhiri** [comment]
Those issues are now managed on RoQ-Backend.
