### ISSUE TITLE
Hosts are not un-registered from GCM if it is stopped first

### ISSUE THREAD

**Issue by jbruggem** [roq-messaging/RoQ#89]
Steps to reproduce:
- start a GCM
- start a Host
- host is registered in GCM
- stop GCM
- stop host
- start GCM

Actual outcome: host is still registered in GCM
Desired outcome: GCM detects that the host is unavailable and acts accordingly (removes it from list? Tags it as offline?)

**Comment by roq-messaging** [comment]
OK. I will :
1. Unregister the host from the GCM (this was not done yet)
2. Clean the config DB when shutting down the GCM

A better solution will arrive with the HA milestone, at that time we will integrate a Zookpeer cluster management solution.

**Comment by roq-messaging** [comment]
TODO: we need to update the Queue configuration in order to let the IP address be the FK. Otherwise the FK information will just be useless as new host can connect after removal with a different order.
