### ISSUE TITLE
Inconsistent return object when requesting an AS Rule

### ISSUE THREAD

**Issue by jbruggem** [roq-messaging/RoQ#90]
When sending a 2007 message to the GCM to request the description of a 
rule, the return message does not fit the usual pattern described below.
`{
    "RESULT": NUMBER,
    "COMMENT": "comment"
}`
Wouldn't it be better to stick to this return structure, adding a third 
non-mandatory element to it (e.g. named "data" or "value") to return
the requested data?

**Comment by sskhiri** [comment]
OK I suppose it would make the client job much more easier. I OK do not see any issue to stick to the usual pattern.
